[project]
name = "posnext_promotions"
authors = [
    { name = "BrainWise", email = "support@brainwise.me"}
]
description = "Standalone ERPNext promotions engine, GWP, coupon extras, and POS authorization gate"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = []

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"
erpnext = ">=15.0.0,<16.0.0"

[tool.ruff]
line-length = 110
target-version = "py310"
